config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'search_queries#index'
  resources :search_queries
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/query.rb
class Query < ApplicationRecord
  has_many :query_results, dependent: :destroy

  def self.create_with_results(query_params:, search_engine: GoogleLinksSearcher.new)
    ActiveRecord::Base.transaction do
      created_query = create!(query_params)
      created_query.update_or_create_query_results(search_engine: search_engine)
    end
  end

  def update_or_create_query_results(search_engine: GoogleLinksSearcher.new)
    search_results = search_engine.run_query(searched_quote)
    search_results.each do |search_result|
      QueryResult.create_or_update_by_link!(query_id: id,
                                          text: search_result.text,
                                          link: search_result.link)
    end
    self
  end
end

app/models/query_result.rb
class QueryResult < ApplicationRecord
  belongs_to :search_query, required: true, counter_cache: true

  def self.create_or_update_by_link(search_query_id:, text:, link:)
    query_result = find_by_search_query_id_and_link(search_query_id, link)
    if query_result.present?
      query_result.update(text: text)
    else
      create(search_query_id: search_query_id, text: text, link: link)
    end
  end
end

app/models/search_query.rb
class SearchQuery < ApplicationRecord
  has_many :query_results, dependent: :delete_all

  def self.create_with_results(search_query_params:, search_engine: GoogleLinksSearcher.new)
    created_query = create(search_query_params)
    created_query.update_or_create_query_results(search_engine: search_engine)
  end

  def update_searched_quote(searched_quote:, search_engine: GoogleLinksSearcher.new )
    transaction do
      update!(searched_quote: searched_quote)
      query_results.delete_all
      update_or_create_query_results(search_engine: search_engine)
    end
  end

  def update_or_create_query_results(search_engine: GoogleLinksSearcher.new)
    search_results = search_engine.run_query(searched_quote)
    search_results.each do |search_result|
      QueryResult.create_or_update_by_link(search_query_id: id,
                                           text: search_result.text,
                                           link: search_result.link)
    end
    self
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/search_queries_controller.rb
class SearchQueriesController < ApplicationController
  before_action :find_query, only: [:show, :edit, :destroy, :update]

  def index
    @search_query = SearchQuery.new
    @search_queries = SearchQuery.includes(:query_results)
  end

  def show; end

  def edit; end

  def destroy
    @search_query.destroy!
    redirect_to search_queries_path, notice: 'Query destroyed!'
  end

  def create
    SearchQuery.create_with_results(search_query_params: search_query_params)
    redirect_to search_queries_path, notice: 'Query created!'
  end

  def update
    @search_query.update_searched_quote(searched_quote: search_query_params[:searched_quote])
    redirect_to search_queries_path, notice: 'Search Query updated!'
  end

  private

  def find_query
    @search_query = SearchQuery.find(params[:id])
  end

  def search_query_params
    params.require(:search_query).permit(:searched_quote)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoogleSearching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <% flash.each do |type, msg| %>
        <div class="alert alert-info flash-alert">
          <%= msg %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/queries/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <%= form_for @query, html: {class: 'form-inline'} do |f| %>
        <div class="form-group mb-2 mr-3">
          <h4>Google Search</h4>
        </div>
        <div class="form-group mb-10">
          <%= f.label :searched_quote, 'Query', class: 'sr-only' %>
          <%= f.text_field :searched_quote, class: "form-control" %>
        </div>
        <%= f.submit 'Search', class: "btn btn-primary mb-2"%>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Query</th>
            <th scope="col">Results count</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @queries.each do |query| %>
            <tr>
              <td>1</td>
              <td><%= query.searched_quote %></td>
              <td><%= query.query_results.size %></td>
              <td>
                <div class="row">
                  <%= link_to 'Details', query, class: 'btn btn-primary' %>
                  <%= link_to 'Edit', edit_query_path(query), class: 'btn btn-primary' %>
                  <%= link_to 'Delete', query, method: :delete, class: 'btn btn-primary', data:{ confirm: 'Are tou sure?' } %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/search_queries/edit.html.erb
<div class="row">
  <div class="col">
    <%= link_to 'Go details', search_query_path(@search_query), class: 'btn btn-primary' %>
    <%= link_to 'Go to list', search_queries_path, class: 'btn btn-primary float-right' %>
  </div>
</div>
<h1 class="text-center">Edit Query</h1>
<div class="card">
  <div class="card-body">
    <%= form_for @search_query do |f| %>
      <div class="form-group">
        <%= f.label :searched_quote, 'Searched quote' %>
        <%= f.text_field :searched_quote, class: 'form-control' %>
      </div>
      <%= f.submit 'Update', class: 'btn btn-success btn-block' %>
    <% end %>
  </div>
</div>

app/views/search_queries/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= form_for @search_query, html: { class: 'form-inline' } do |f| %>
      <div class="form-group mx-3">
        <h4>Google Search</h4>
      </div>
      <div class="form-group mr-3 ">
        <%= f.label :searched_quote, 'Query', class: 'sr-only' %>
        <%= f.text_field :searched_quote, class: "form-control" %>
      </div>
      <%= f.submit 'Search', class: "btn btn-primary"%>
    <% end %>
  </div>
</div>
<div class="row mt-4">
  <div class="col-xs-12 table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Query</th>
          <th scope="col">Results count</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @search_queries.each do |search_query| %>
          <tr>
            <td>1</td>
            <td><%= search_query.searched_quote %></td>
            <td><%= search_query.query_results.count %></td>
            <td>
              <div class="btn-group" role="group" >
                <%= link_to 'Details', search_query, class: 'btn btn-primary' %>
                <%= link_to 'Edit', edit_search_query_path(search_query), class: 'btn btn-primary' %>
                <%= link_to 'Delete', search_query, method: :delete, class: 'btn btn-primary', data: { confirm: 'Are tou sure?' } %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/search_queries/show.html.erb
<div class="row">
  <div class="col">
    <%= link_to 'Go back', search_queries_path, class: 'btn btn-primary' %>
    <%= link_to 'Edit', edit_search_query_path(@search_query), class: 'float-right btn btn-primary' %>
  </div>
</div>
<h1 align="center">Query details</h1>
<div class="card shadow">
  <div class="card-body">
    <div class="row">
      <div class="col">
        <strong>Searched phrase:</strong> <%= @search_query.searched_quote %>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <strong>Query results count:</strong> <%= @search_query.query_results.count %>
      </div>
    </div>
    <div class="card mt-4">
      <div class="card-header">
        <h5 class="mt-1">Query results</h3>
      </div>
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Title</th>
              <th scope="col">Link</th>
            </tr>
          </thead>
          <tbody>
            <% @search_query.query_results.each do |query_result| %>
              <tr scope="row">
                <td><%= query_result.text %></td>
                <td><%= link_to 'Go to page', query_result.link, class: 'btn btn-success btn-sm',style:'white-space: nowrap' %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>